### ISSUE TITLE
Unknown team for Basic Example Project

### ISSUE THREAD

**Issue by ghost** [intellum/neeman#11]
Team settings have been pushed to the repo.

<img width="555" alt="screenshot 2018-11-28 at 14 36 10" src="https://user-images.githubusercontent.com/14126999/49158878-15c99880-f31b-11e8-8229-404e92d52d92.png">

**Comment by rob-nash** [comment]
I will submit a pull request for this.

**Comment by ghost** [comment]
Recommend switching to 'none' for demo App and committing that.
