### ISSUE TITLE
Quickstart not so quick

### ISSUE THREAD

**Issue by ghost** [intellum/neeman#18]
The QuickStart instructions suggest that a field named 'URL String' will become available in the storyboard.

I don't have that option.

<img width="1017" alt="screenshot 2018-11-28 at 14 45 49" src="https://user-images.githubusercontent.com/14126999/49159386-5249c400-f31c-11e8-9762-27f4811b7b3d.png">
<img width="1018" alt="screenshot 2018-11-28 at 14 45 42" src="https://user-images.githubusercontent.com/14126999/49159390-54138780-f31c-11e8-8296-a248d2f8bc9c.png">

**Comment by onato** [comment]
I wasn't able to reproduce this. Is the field appearing again now?

**Comment by ghost** [comment]
Ye issue's closed. 

It seems the work you did [here](https://github.com/intellum/neeman/commit/dde2b378e8b28a8541c3f441f67b4e78f7c459a7) fixed it.

**Comment by onato** [comment]
Nope. Xcode should just pick that up from the @IBInspectable [here](https://github.com/intellum/neeman/blob/master/Source/WebViewController.swift#L76). I'm can't think why it wouldn't have been working. Anyway, I'll keep an eye out for it happening again in future.
